"""
setup_env.py
============
Interactive helper that creates your local `.env` file step by step.

Why this exists:
    Hand-editing `.env` is error-prone (stray spaces, quotes, wrong names).
    This script asks you for each value, validates the obvious mistakes
    (empty values, quotes, spaces), and writes a clean `.env` for you.

Usage:
    python setup_env.py

It will NOT overwrite an existing `.env` unless you confirm.
Nothing is sent anywhere; the file stays on your machine and is git-ignored.
"""

import os
import sys

# Windows consoles default to cp1252; force UTF-8 so nothing crashes.
try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except (AttributeError, ValueError):  # pragma: no cover - very old Python
    pass

HERE = os.path.dirname(os.path.abspath(__file__))
ENV_PATH = os.path.join(HERE, ".env")
EXAMPLE_PATH = os.path.join(HERE, ".env.example")


def _ask(prompt: str, default: str = "", required: bool = True) -> str:
    """Ask for a value, strip stray quotes/spaces, and validate emptiness."""
    while True:
        suffix = f" [{default}]" if default else ""
        raw = input(f"{prompt}{suffix}: ").strip()
        if not raw and default:
            raw = default
        # Strip accidental surrounding quotes that people paste from docs.
        if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in {"'", '"'}:
            raw = raw[1:-1].strip()
        if not raw and required:
            print("  ! This value is required. Please enter it.")
            continue
        return raw


def _confirm(prompt: str) -> bool:
    return input(f"{prompt} [y/N]: ").strip().lower() in {"y", "yes"}


def main() -> None:
    print("\n" + "=" * 70)
    print("Cinevo Bot - Interactive .env setup")
    print("=" * 70)
    print("This creates the local .env file used for testing on your machine.")
    print("Press Enter to accept the [default] shown in brackets.\n")

    if os.path.exists(ENV_PATH):
        print(f"! A .env file already exists at:\n    {ENV_PATH}")
        if not _confirm("Overwrite it?"):
            print("Aborted. Your existing .env was left untouched.")
            sys.exit(0)
        print()

    # ------------------------------------------------------------------ #
    # 1. DeepSeek
    # ------------------------------------------------------------------ #
    print("-" * 70)
    print("STEP 1/4 - DeepSeek AI")
    print("Get your key at: https://platform.deepseek.com/api_keys")
    print("-" * 70)
    deepseek_key = _ask("DEEPSEEK_API_KEY (starts with sk-)")

    # ------------------------------------------------------------------ #
    # 2. YouTube API key (read comments)
    # ------------------------------------------------------------------ #
    print("\n" + "-" * 70)
    print("STEP 2/4 - YouTube API key (for READING comments)")
    print("Google Cloud Console -> APIs & Services -> Credentials -> API key")
    print("IMPORTANT: enable 'YouTube Data API v3' for the project first.")
    print("-" * 70)
    youtube_key = _ask("YOUTUBE_API_KEY")

    # ------------------------------------------------------------------ #
    # 3. YouTube OAuth token (post replies) - optional
    # ------------------------------------------------------------------ #
    print("\n" + "-" * 70)
    print("STEP 3/4 - YouTube OAuth token (for POSTING replies) - optional")
    print("Needs scope: https://www.googleapis.com/auth/youtube.force-ssl")
    print("Leave empty to test reading only (the bot will not post).")
    print("-" * 70)
    youtube_oauth = _ask("YOUTUBE_OAUTH_TOKEN", required=False)

    # ------------------------------------------------------------------ #
    # 4. Platforms
    # ------------------------------------------------------------------ #
    print("\n" + "-" * 70)
    print("STEP 4/4 - Which platforms to run")
    print("For local testing we recommend just 'youtube'.")
    print("-" * 70)
    platforms = _ask("ACTIVE_PLATFORMS", default="youtube")

    # ------------------------------------------------------------------ #
    # Write the file
    # ------------------------------------------------------------------ #
    lines = [
        "# Auto-generated by setup_env.py - DO NOT COMMIT THIS FILE.",
        "#",
        "# Master switch",
        "BOT_ENABLED=true",
        f"ACTIVE_PLATFORMS={platforms}",
        "",
        "# DeepSeek AI",
        f"DEEPSEEK_API_KEY={deepseek_key}",
        "DEEPSEEK_BASE_URL=https://api.deepseek.com",
        "DEEPSEEK_MODEL=deepseek-chat",
        "DEEPSEEK_MAX_TOKENS=120",
        "DEEPSEEK_TEMPERATURE=0.7",
        "",
        "# Brand",
        "WEBSITE_URL=https://cinevoapp.com",
        "BRAND_NAME=Cinevo",
        "",
        "# Targets",
        "TARGETS_FILE=targets.json",
        "MAX_TARGETS_PER_PLATFORM=0",
        "",
        "# YouTube",
        "YOUTUBE_ENABLED=true",
        f"YOUTUBE_API_KEY={youtube_key}",
        f"YOUTUBE_OAUTH_TOKEN={youtube_oauth}",
        "YOUTUBE_VIDEO_IDS=",
        "YOUTUBE_CHANNEL_IDS=",
        "",
        "# Meta (disabled for local test)",
        "META_ENABLED=false",
        "META_ACCESS_TOKEN=",
        "META_API_VERSION=v19.0",
        "FACEBOOK_PAGE_IDS=",
        "INSTAGRAM_BUSINESS_IDS=",
        "",
        "# TikTok (disabled)",
        "TIKTOK_ENABLED=false",
        "TIKTOK_ACCESS_TOKEN=",
        "TIKTOK_OPEN_ID=",
        "TIKTOK_VIDEO_IDS=",
        "TIKTOK_BROWSER_AUTOMATION=false",
        "",
        "# Quora (disabled)",
        "QUORA_ENABLED=false",
        "QUORA_TOPICS=movies,series",
        "QUORA_USERNAME=",
        "QUORA_PASSWORD=",
        "QUORA_BROWSER_AUTOMATION=false",
        "",
        "# Anti-ban / rate limiting",
        "MIN_DELAY_SECONDS=180",
        "MAX_DELAY_SECONDS=420",
        "POLL_INTERVAL_SECONDS=300",
        "MAX_COMMENTS_PER_CYCLE=20",
        "",
        "# Database & logging",
        "DB_PATH=bot_state.db",
        "LOG_LEVEL=INFO",
        "LOG_FILE=logs/bot.log",
        "",
    ]

    try:
        with open(ENV_PATH, "w", encoding="utf-8") as fh:
            fh.write("\n".join(lines))
    except OSError as exc:
        print(f"\n! Could not write .env: {exc}")
        sys.exit(1)

    print("\n" + "=" * 70)
    print(f"OK - .env written to:\n    {ENV_PATH}")
    print("=" * 70)
    print("Next step: run the diagnostic to verify everything works:")
    print("    python check_setup.py")
    print()


if __name__ == "__main__":
    main()
