"""
video_composer.py
=================
Stitches transformed clips into a finished vertical Short, adding:

    * a hook / caption overlay (drawtext, per-scene fade)
    * an optional AI voiceover (edge-tts, generated by video_maker)
    * an optional royalty-free music bed (ducked under the voiceover)
    * a brand watermark

This is the "assembly" stage of the VPS trailer pipeline:

    trailer_downloader.py  ->  clip_processor.py  ->  video_composer.py
                                                          |
                                                    youtube_uploader.py

DESIGN
    * FFmpeg is invoked as a SUBPROCESS; a missing binary degrades gracefully.
    * The composer NEVER raises: on any failure it returns None so the
      orchestrator can fall back to the text-only video_maker.
    * Audio is mixed with `amix` + `sidechaincompress`-free ducking (a simple
      volume expression) to keep the filter graph portable across FFmpeg
      versions found on typical VPS images.

USAGE (CLI)
    python video_composer.py --clips trailer_output/Sinister_clip01.mp4 \
        --hook "This movie made me sleep with the lights on." --out out.mp4
    python video_composer.py --check

USAGE (code)
    from video_composer import video_composer
    path = video_composer.compose(clips, hook="...", out_path=Path("out.mp4"))
"""

from __future__ import annotations

import argparse
import logging
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import List, Optional, Sequence

try:  # Windows consoles are cp1252 by default; keep logs readable.
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except (AttributeError, ValueError):  # pragma: no cover
    pass

from config import settings

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Output geometry (must match clip_processor)
# ---------------------------------------------------------------------------

OUT_WIDTH = 1080
OUT_HEIGHT = 1920
OUT_FPS = 30

#: Fonts to try, in order. DejaVu/Liberation ship with most Linux images;
#: the rest are Windows fallbacks for local testing.
_FONT_CANDIDATES = (
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    "C:/Windows/Fonts/arialbd.ttf",
    "C:/Windows/Fonts/arial.ttf",
    "C:/Windows/Fonts/segoeuib.ttf",
)


def _find_font() -> Optional[str]:
    """Return the first available font path, or None."""
    for candidate in _FONT_CANDIDATES:
        if os.path.isfile(candidate):
            return candidate
    return None


def _find_ffmpeg() -> Optional[str]:
    """Locate the ffmpeg binary (PATH first, then common install spots)."""
    found = shutil.which("ffmpeg")
    if found:
        return found
    for candidate in (
        r"C:\ffmpeg\bin\ffmpeg.exe",
        r"C:\Program Files\ffmpeg\bin\ffmpeg.exe",
        "/usr/bin/ffmpeg",
        "/usr/local/bin/ffmpeg",
    ):
        if os.path.isfile(candidate):
            return candidate
    return None


def _escape_drawtext(text: str) -> str:
    """
    Escape a string for FFmpeg's drawtext filter.

    drawtext treats ':' '\\' '%' and the quoting characters specially, and
    the whole filter is passed through a shell-free argv list, so we only
    need to escape for FFmpeg itself.
    """
    text = text.replace("\\", "\\\\")
    text = text.replace(":", "\\:")
    text = text.replace("'", "\u2019")  # curly apostrophe avoids quoting hell
    text = text.replace("%", "\\%")
    text = text.replace(",", "\\,")
    text = text.replace("[", "\\[")
    text = text.replace("]", "\\]")
    text = text.replace(";", "\\;")
    return text


def _wrap(text: str, width: int = 22) -> str:
    """Greedy word-wrap; drawtext renders '\\n' as a line break."""
    words = text.split()
    lines: List[str] = []
    current = ""
    for word in words:
        candidate = f"{current} {word}".strip()
        if len(candidate) <= width:
            current = candidate
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return "\n".join(lines[:4])  # never more than 4 lines on screen


class VideoComposer:
    """Assembles transformed clips + text + audio into a finished Short."""

    def __init__(self) -> None:
        self._ffmpeg = _find_ffmpeg()
        self._font = _find_font()

    # ------------------------------------------------------------------ #
    # Capability
    # ------------------------------------------------------------------ #
    def available(self) -> bool:
        """True when FFmpeg is present and the trailer pipeline is enabled."""
        if not getattr(settings, "trailer_enabled", False):
            logger.debug("VideoComposer: TRAILER_ENABLED is false.")
            return False
        if not self._ffmpeg:
            logger.warning("VideoComposer: ffmpeg not found on PATH.")
            return False
        return True

    @property
    def font(self) -> Optional[str]:
        return self._font

    # ------------------------------------------------------------------ #
    # Concatenation
    # ------------------------------------------------------------------ #
    def _concat(
        self, clips: Sequence[Path], work_dir: Path, out_path: Path
    ) -> bool:
        """
        Concatenate clips with the concat demuxer (stream copy, no re-encode).

        All clips come out of clip_processor with identical codec/geometry,
        so a stream copy is safe and fast.
        """
        if not self._ffmpeg:
            return False

        list_file = work_dir / "concat.txt"
        try:
            with list_file.open("w", encoding="utf-8") as handle:
                for clip in clips:
                    # The concat demuxer needs single quotes escaped.
                    safe = str(clip.resolve()).replace("'", "'\\''")
                    handle.write(f"file '{safe}'\n")
        except OSError as exc:
            logger.warning("VideoComposer: cannot write concat list: %s", exc)
            return False

        cmd = [
            self._ffmpeg,
            "-hide_banner",
            "-loglevel", "error",
            "-y",
            "-f", "concat",
            "-safe", "0",
            "-i", str(list_file),
            "-c", "copy",
            "-movflags", "+faststart",
            str(out_path),
        ]
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
        except subprocess.SubprocessError as exc:
            logger.warning("VideoComposer: concat failed: %s", exc)
            return False

        if result.returncode != 0:
            logger.warning(
                "VideoComposer: concat returned %s: %s",
                result.returncode,
                (result.stderr or "").strip()[:400],
            )
            return False
        return out_path.is_file() and out_path.stat().st_size > 0

    # ------------------------------------------------------------------ #
    # Overlay + audio
    # ------------------------------------------------------------------ #
    def _overlay_filter(self, hook: str) -> str:
        """Build the drawtext chain for the hook + brand watermark."""
        parts: List[str] = []

        if hook and self._font:
            font = self._font.replace("\\", "/").replace(":", "\\:")
            wrapped = _escape_drawtext(_wrap(hook))
            # Hook: centred, upper third, with a soft shadow for legibility.
            parts.append(
                "drawtext="
                f"fontfile='{font}':"
                f"text='{wrapped}':"
                "fontcolor=white:fontsize=64:line_spacing=14:"
                "borderw=4:bordercolor=black@0.85:"
                "shadowx=3:shadowy=3:shadowcolor=black@0.6:"
                "x=(w-text_w)/2:y=h*0.16:"
                "alpha='if(lt(t,0.4),t/0.4,1)'"
            )

        brand = getattr(settings, "brand_name", "") or ""
        if brand and self._font:
            font = self._font.replace("\\", "/").replace(":", "\\:")
            parts.append(
                "drawtext="
                f"fontfile='{font}':"
                f"text='{_escape_drawtext(brand)}':"
                "fontcolor=white@0.55:fontsize=38:"
                "borderw=2:bordercolor=black@0.5:"
                "x=w-text_w-40:y=h-120"
            )

        return ",".join(parts) if parts else "null"

    def _audio_inputs(
        self, voiceover: Optional[Path], music: Optional[Path]
    ) -> tuple[List[str], str]:
        """
        Build the -i arguments and the audio filter chain.

        Returns (input_args, filter_complex_audio_label).
        """
        inputs: List[str] = []
        chains: List[str] = []
        labels: List[str] = []

        if voiceover and Path(voiceover).is_file():
            inputs += ["-i", str(voiceover)]
            chains.append(f"[{len(inputs) // 2}:a]volume=1.0[vo]")
            labels.append("[vo]")

        if music and Path(music).is_file():
            inputs += ["-stream_loop", "-1", "-i", str(music)]
            # Duck the music under the voiceover: 0.18 when a voiceover is
            # present, 0.35 when it plays alone.
            level = 0.18 if labels else 0.35
            chains.append(f"[{len(inputs) // 2}:a]volume={level}[bg]")
            labels.append("[bg]")

        if not labels:
            return inputs, ""

        if len(labels) == 1:
            return inputs, f"{''.join(chains)};{labels[0]}anull[amixout]"

        chains.append(
            f"{''.join(labels)}amix=inputs={len(labels)}:"
            "duration=first:dropout_transition=2[amixout]"
        )
        return inputs, ";".join(chains)

    # ------------------------------------------------------------------ #
    # Public API
    # ------------------------------------------------------------------ #
    def compose(
        self,
        clips: Sequence[Path],
        hook: str = "",
        out_path: Optional[Path] = None,
        voiceover: Optional[Path] = None,
        music: Optional[Path] = None,
    ) -> Optional[Path]:
        """
        Assemble `clips` into a finished Short.

        Returns the output path on success, or None on any failure.
        Never raises.
        """
        clips = [Path(c) for c in clips if Path(c).is_file()]
        if not clips:
            logger.warning("VideoComposer: no usable clips supplied.")
            return None

        if not self.available():
            return None

        out_path = Path(out_path) if out_path else Path("composed_short.mp4")
        out_path.parent.mkdir(parents=True, exist_ok=True)
        work_dir = out_path.parent / ".compose_work"
        work_dir.mkdir(parents=True, exist_ok=True)

        # 1) Concatenate the clips into one silent-ish track.
        joined = work_dir / "joined.mp4"
        if not self._concat(clips, work_dir, joined):
            logger.warning("VideoComposer: concatenation failed.")
            return None

        # 2) Apply the text overlay and mix the audio.
        vf = self._overlay_filter(hook)
        audio_inputs, audio_filter = self._audio_inputs(voiceover, music)

        cmd: List[str] = [
            self._ffmpeg,
            "-hide_banner",
            "-loglevel", "error",
            "-y",
            "-i", str(joined),
        ]
        cmd += audio_inputs

        if audio_filter:
            # Keep the trailer's own audio at a low bed level and mix in the
            # voiceover / music on top.
            filter_complex = (
                f"[0:a]volume=0.25[src];{audio_filter};"
                "[src][amixout]amix=inputs=2:duration=first:"
                "dropout_transition=2[aout]"
            )
            cmd += [
                "-filter_complex", filter_complex,
                "-map", "0:v:0",
                "-map", "[aout]",
            ]
        else:
            cmd += ["-map", "0:v:0", "-map", "0:a?"]

        cmd += [
            "-vf", vf,
            "-c:v", "libx264",
            "-preset", "veryfast",
            "-crf", "20",
            "-pix_fmt", "yuv420p",
            "-r", str(OUT_FPS),
            "-c:a", "aac",
            "-b:a", "160k",
            "-ar", "44100",
            "-shortest",
            "-movflags", "+faststart",
            str(out_path),
        ]

        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=900)
        except subprocess.SubprocessError as exc:
            logger.warning("VideoComposer: compose failed: %s", exc)
            return None

        if result.returncode != 0:
            logger.warning(
                "VideoComposer: ffmpeg returned %s: %s",
                result.returncode,
                (result.stderr or "").strip()[:600],
            )
            return None

        if not out_path.is_file() or out_path.stat().st_size == 0:
            logger.warning("VideoComposer: output missing or empty.")
            return None

        logger.info(
            "VideoComposer: wrote %s (%.1f KB)",
            out_path.name,
            out_path.stat().st_size / 1024,
        )
        return out_path

    def duration(self, path: Path) -> float:
        """Return the duration of a media file in seconds (0.0 on failure)."""
        if not self._ffmpeg or not Path(path).is_file():
            return 0.0
        try:
            out = subprocess.run(
                [self._ffmpeg, "-i", str(path)],
                capture_output=True, text=True, timeout=60,
            )
        except subprocess.SubprocessError:
            return 0.0
        blob = (out.stderr or "") + (out.stdout or "")
        import re

        match = re.search(r"Duration:\s*(\d+):(\d+):(\d+\.?\d*)", blob)
        if not match:
            return 0.0
        hours, minutes, seconds = (
            int(match.group(1)), int(match.group(2)), float(match.group(3))
        )
        return hours * 3600 + minutes * 60 + seconds


# A single, importable instance used across the whole application.
video_composer = VideoComposer()


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def _cmd_check() -> int:
    composer = VideoComposer()
    print(f"ffmpeg : {composer._ffmpeg or 'NOT FOUND'}")
    print(f"font   : {composer._font or 'NOT FOUND'}")
    print(f"enabled: {getattr(settings, 'trailer_enabled', False)}")
    return 0 if composer._ffmpeg else 1


def _cmd_compose(args: argparse.Namespace) -> int:
    composer = VideoComposer()
    if not composer.available():
        print("VideoComposer is not available (ffmpeg missing or TRAILER_ENABLED=false).")
        return 1

    clips = [Path(p) for p in args.clips]
    voiceover = Path(args.voiceover) if args.voiceover else None
    music = Path(args.music) if args.music else (
        Path(settings.trailer_music_path) if settings.trailer_music_path else None
    )

    out = composer.compose(
        clips,
        hook=args.hook or "",
        out_path=Path(args.out),
        voiceover=voiceover,
        music=music,
    )
    if not out:
        print("Composition failed.")
        return 1
    print(f"Wrote {out} ({composer.duration(out):.1f}s)")
    return 0


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Compose transformed clips into a finished vertical Short."
    )
    sub = parser.add_subparsers(dest="command")

    p_check = sub.add_parser("check", help="Show ffmpeg/font availability.")
    p_check.set_defaults(func=lambda a: _cmd_check())

    p_compose = sub.add_parser("compose", help="Assemble clips into a Short.")
    p_compose.add_argument("--clips", nargs="+", required=True, help="Clip paths.")
    p_compose.add_argument("--hook", default="", help="Overlay hook text.")
    p_compose.add_argument("--out", required=True, help="Output MP4 path.")
    p_compose.add_argument("--voiceover", default=None, help="Voiceover audio file.")
    p_compose.add_argument("--music", default=None, help="Music bed file.")
    p_compose.set_defaults(func=_cmd_compose)

    args = parser.parse_args(argv)
    if not getattr(args, "func", None):
        parser.print_help()
        return 0
    return args.func(args)


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)-7s | %(name)s | %(message)s",
    )
    raise SystemExit(main())
